using XmiSchema.Core.Entities;
using XmiSchema.Core.Relationships;

namespace XmiSchema.Core.Models;

/// <summary>
/// Root container representing a complete Cross Model Information (XMI) graph model.
/// </summary>
/// <remarks>
/// <para>
/// `XmiModel` is the central data structure in the XMI schema, representing the entire built
/// environment data model as a directed graph. It contains two primary collections:
/// </para>
/// <list type="bullet">
/// <item><description><b>Entities</b>: The nodes in the graph (structural members, materials, geometry, etc.)</description></item>
/// <item><description><b>Relationships</b>: The directed edges connecting entities (has-a, references, etc.)</description></item>
/// </list>
/// <para>
/// This graph-based approach enables flexible representation of complex structural engineering
/// data with explicit relationships, supporting advanced queries, traversals, and analysis.
/// </para>
/// <para>
/// Models are typically constructed using <see cref="XmiSchemaModelBuilder"/>, which provides
/// a fluent API for adding entities and automatically inferring relationships.
/// </para>
/// <para>
/// The model can be exported to JSON format as a graph structure with nodes and edges, making
/// it interoperable with various data analysis and visualization tools.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // Create and populate a model
/// var model = new XmiModel();
/// model.Entities.Add(material);
/// model.Entities.Add(crossSection);
/// model.Relationships.Add(new XmiHasStructuralMaterial(crossSection, material));
///
/// // Export to JSON
/// var jsonBuilder = new ExtensionNativeJsonBuilder(model);
/// string json = jsonBuilder.BuildJson();
/// </code>
/// </example>
public class XmiModel
{
    /// <summary>
    /// Gets or sets the collection of all entities in the model.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Entities represent the nodes in the graph and include:
    /// </para>
    /// <list type="bullet">
    /// <item><description>Structural elements (beams, columns, slabs, walls)</description></item>
    /// <item><description>Material definitions (concrete, steel, timber)</description></item>
    /// <item><description>Cross-section properties</description></item>
    /// <item><description>Geometric primitives (points, lines, arcs)</description></item>
    /// <item><description>Organizational elements (storeys, units)</description></item>
    /// <item><description>Segments and nodes</description></item>
    /// </list>
    /// <para>
    /// Each entity must have a unique ID within the model. The collection is initialized
    /// as an empty list and populated during model construction.
    /// </para>
    /// <para>
    /// Entities can be of any type derived from <see cref="XmiBaseEntity"/>, allowing
    /// heterogeneous collections representing the complete structural model.
    /// </para>
    /// </remarks>
    public List<XmiBaseEntity> Entities { get; set; } = new();

    /// <summary>
    /// Gets or sets the collection of all relationships in the model.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Relationships represent the directed edges in the graph and define how entities
    /// are connected. Each relationship has a source entity and a target entity, forming
    /// a directed connection with semantic meaning.
    /// </para>
    /// <para>
    /// Common relationship types include:
    /// </para>
    /// <list type="bullet">
    /// <item><description><b>XmiHasGeometry</b>: Entity → Geometric representation</description></item>
    /// <item><description><b>XmiHasStructuralMaterial</b>: CrossSection/Surface → Material</description></item>
    /// <item><description><b>XmiHasStructuralCrossSection</b>: CurveMember → CrossSection</description></item>
    /// <item><description><b>XmiHasStructuralNode</b>: Member/Segment → Node</description></item>
    /// <item><description><b>XmiHasSegment</b>: Member → Segment</description></item>
    /// <item><description><b>XmiHasStructuralStorey</b>: Entity → Storey</description></item>
    /// </list>
    /// <para>
    /// Relationships are typically auto-generated by <see cref="ExtensionRelationshipExporter"/>
    /// during the model building process, but can also be added manually.
    /// </para>
    /// <para>
    /// The collection is initialized as an empty list and populated with inferred or
    /// explicit relationships.
    /// </para>
    /// </remarks>
    public List<XmiBaseRelationship> Relationships { get; set; } = new();
}

